<?php
use yii\bootstrap4\Breadcrumbs;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;
use common\helpers\Custom;
use common\helpers\Security;
use common\models\StudentCourse;
use frontend\models\StudentGroups;
use frontend\models\ClassRoomSecurity;
use common\models\User;

/* @var $this yii\web\View */
$this->params['courseTitle'] ="<i class='fa fa-group'></i> ".$cid." Groups";
$this->title = $cid." Groups";
$this->params['breadcrumbs'] = [
  ['label'=>$cid.' Dashboard', 'url'=>Url::to(['/instructor/class-dashboard', 'cid'=>ClassRoomSecurity::encrypt($cid)])],
  ['label'=>$cid.' Students', 'url'=>Url::to(['/instructor/class-students', 'cid'=>ClassRoomSecurity::encrypt($cid)])],
  ['label'=>$this->title]
];

?>




      <div class="row">
        <div class="col-md-12">
        <a href="#" class="btn btn-sm btn-info btn-rounded float-right mb-2" data-target="#studentmodal" data-toggle="modal"><i class="fas fa-plus-circle" ></i> Students groups type</a>
        <a href="#" class="btn btn-sm btn-info btn-rounded float-right mb-2" data-target="#mymodal" data-toggle="modal" style="margin-right:10px"><i class="fa fa-cog" ></i> Generate New Groups</a>
     
        </div>
                  
      </div>
<?php if($groups!=null){foreach($groups as $group)  {?>
<div class="accordion" id="accordionExample">
  <div class="card" >
    <div class="card-header p-2" id="heading">
      <h2 class="mb-0">
      <div class="row">
      <div class="col-sm-7" data-toggle="collapse" data-target="#collapse<?=$group->typeID?>" aria-expanded="true" aria-controls="collapse">
      <button class="btn btn-link btn-block text-left col-md-11" type="button" >
        <i class="fas fa-clipboard-list"></i> <?=Html::encode($group->generation_type);?>
        </button>
      </div>
      <div class="col-sm-3" data-toggle="collapse" data-target="#collapse<?=$group->typeID?>" aria-expanded="true" aria-controls="collapse" style="cursor:pointer">
      <span style="font-size:12px; color:#ccc">Generated by <?=Html::encode($group->instructor->full_name); ?></span>
      </div>
      <div class="col-sm-1">
      <a href="#" ccode=<?=$group->typeID;?> class="grpdelete"><button  class="float-right btn btn-link"><span><i class="fas fa-trash" style="font-size:17px"></i></span></button></a>
      </div>
      
      <div class="col-sm-1" data-toggle="collapse" data-target="#collapse<?=$group->typeID?>" aria-expanded="true" aria-controls="collapse" style="cursor:pointer">
      <i class="fas fa-ellipsis-v float-right text-secondary text-sm"></i>
      </div>
      </div>
         
       
      </h2>
    </div>

    <div id="collapse<?=$group->typeID?>" class="collapse" aria-labelledby="heading" data-parent="#accordionExample">
      <div class="card-body">
         <div class="card-footer p-0">
                <?php for($g=0;$g<count($group->groups);$g++){?>
                  <div class="accordion" id="grpaccord">
                  <div  class="card" data-toggle="collapse" data-target="#grpstud<?=$group->groups[$g]->groupID?>" aria-expanded="true" aria-controls="collapse">
                  <div class="card-header p-2" id="grouphead" style="border:none; border-radius:none;box-shadow:none; border-color:none">
                  <i class="fas fa-group"></i> <span style="color: green" ><?php print $group->groups[$g]->groupName; ?></span> 
                   </div>
                   </div>
                  <div id="grpstud<?=$group->groups[$g]->groupID?>" class="collapse" aria-labelledby="heading" data-parent="#grpaccord">
                  <div class="row" style="font-size:12px;background-color:lightblue">
                  <div class="col-sm-1">s/no</div>
                  <div class="col-sm-5">full name</div>
                  <div class="col-sm-4">reg #</div>
                  <div class="col-sm-1">program</div>
                  <div class="col-sm-1">YOS</div>
                  </div>
                  <?php for($st=0;$st<count($group->groups[$g]->studentGroups);$st++){?>
             
                  <div class="row" style="font-size:12px">
                  <div class="col-sm-1"><?php print $st+1; ?></div>
                  <div class="col-sm-5"><?=Html::encode($group->groups[$g]->studentGroups[$st]->regNo->fname." ".$group->groups[$g]->studentGroups[$st]->regNo->mname." ".$group->groups[$g]->studentGroups[$st]->regNo->lname); ?></div>
                  <div class="col-sm-4"><?=Html::encode($group->groups[$g]->studentGroups[$st]->regNo->reg_no); ?></div>
                  <div class="col-sm-1"><?=Html::encode( $group->groups[$g]->studentGroups[$st]->regNo->programCode); ?></div>
                  <div class="col-sm-1"><?=Html::encode( $group->groups[$g]->studentGroups[$st]->regNo->YOS); ?></div>
                  </div>
                  <?php } ?>
                  </div>
                  </div>
                  <?php }?>
              </div> 
      </div>
    </div>
  </div>

  <?php 
      
  }
}
        ?>
<!-- ################################################## model for new groups################################  -->

<?php 
$studentGroups = new StudentGroups();
?>
<?= $this->render('students/generate_group',['studentGroups'=>$studentGroups]) ?>
<?php 
$studentGroups = new StudentGroups();
?>
<?= $this->render('students/addStudentGenerationType',['studentGroups'=>$studentGroups]) ?>


</div>

</div>

<?php
$script = <<<JS
 $(document).on('click', '.grpdelete', function(){
  var ccode = $(this).attr('ccode');
  Swal.fire({
  title: 'Are you sure?',
  text: "You won't be able to revert this!",
  icon: 'question',
  showCancelButton: true,
  confirmButtonColor: '#3085d6',
  cancelButtonColor: '#d33',
  confirmButtonText: 'Yes, delete it!'
}).then((result) => {
  if (result.isConfirmed) {
 
    $.ajax({
      url:'/instructor/delete-groups',
      method:'get',
      async:false,
      dataType:'JSON',
      data:{groupgenerationid:ccode},
      success:function(data){
       
          Swal.fire(
              'deleted!',
              "",
              'success'
    )
    setTimeout(function(){
      window.location.reload();
    }, 1500);
   

        
      }
    })
   
  }
})

})

JS;
$this->registerJs($script);
?>